-- supabase/migrations/20260801_create_orders.sql
-- Migration file to create orders and order_items tables, set up security policies, and create a transactional RPC.

-- 1. Create Orders Table
create table if not exists public.orders (
    id uuid primary key default gen_random_uuid(),
    order_number bigint generated by default as identity unique,
    customer_name text not null,
    customer_phone text not null,
    shipping_method text not null check (shipping_method in ('retiro', 'envio')),
    street text,
    floor text,
    department text,
    status text not null default 'pending' check (status in ('pending', 'confirmed', 'preparing', 'ready', 'delivered', 'cancelled')),
    subtotal numeric(12,2) not null check (subtotal >= 0),
    total numeric(12,2) not null check (total >= 0),
    customer_notes text,
    idempotency_key text unique,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Constraint for street requirement when shipping_method = 'envio'
alter table public.orders drop constraint if exists check_shipping_street;
alter table public.orders add constraint check_shipping_street 
    check (shipping_method <> 'envio' or (street is not null and trim(street) <> ''));

-- 2. Create Order Items Table
create table if not exists public.order_items (
    id uuid primary key default gen_random_uuid(),
    order_id uuid not null references public.orders(id) on delete cascade,
    product_id uuid references public.products(id) on delete set null,
    product_name text not null,
    product_brand text,
    unit_price numeric(12,2) not null check (unit_price >= 0),
    quantity integer not null check (quantity > 0),
    subtotal numeric(12,2) not null check (subtotal >= 0),
    created_at timestamptz not null default now()
);

-- 3. Enable Row Level Security (RLS)
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

-- 4. Drop and Create Policies for authenticated admins
drop policy if exists "Allow authenticated admins to manage orders" on public.orders;
create policy "Allow authenticated admins to manage orders" on public.orders
    for all to authenticated using (true) with check (true);

drop policy if exists "Allow authenticated admins to manage order items" on public.order_items;
create policy "Allow authenticated admins to manage order items" on public.order_items
    for all to authenticated using (true) with check (true);

-- 5. Create Transactional RPC function
create or replace function public.create_order_transaction(
    p_customer_name text,
    p_customer_phone text,
    p_shipping_method text,
    p_street text,
    p_floor text,
    p_department text,
    p_customer_notes text,
    p_idempotency_key text,
    p_subtotal numeric,
    p_total numeric,
    p_items jsonb
)
returns table (
    id uuid,
    order_number bigint,
    total numeric,
    created_at timestamp with time zone
)
language plpgsql
security definer
as $$
declare
    v_order_id uuid;
    v_order_number bigint;
    v_created_at timestamp with time zone;
    v_existing_id uuid;
    v_existing_order_number bigint;
    v_existing_total numeric;
    v_existing_created_at timestamp with time zone;
begin
    -- Check for idempotency
    if p_idempotency_key is not null then
        select o.id, o.order_number, o.total, o.created_at
        into v_existing_id, v_existing_order_number, v_existing_total, v_existing_created_at
        from public.orders o
        where o.idempotency_key = p_idempotency_key
        limit 1;
        
        if found then
            return query select v_existing_id, v_existing_order_number, v_existing_total, v_existing_created_at;
            return;
        end if;
    end if;

    -- Insert order
    insert into public.orders (
        customer_name,
        customer_phone,
        shipping_method,
        street,
        floor,
        department,
        customer_notes,
        idempotency_key,
        subtotal,
        total
    ) values (
        p_customer_name,
        p_customer_phone,
        p_shipping_method,
        p_street,
        p_floor,
        p_department,
        p_customer_notes,
        p_idempotency_key,
        p_subtotal,
        p_total
    )
    returning public.orders.id, public.orders.order_number, public.orders.created_at
    into v_order_id, v_order_number, v_created_at;

    -- Insert order items
    insert into public.order_items (
        order_id,
        product_id,
        product_name,
        product_brand,
        unit_price,
        quantity,
        subtotal
    )
    select
        v_order_id,
        case 
            when (item->>'product_id') is not null and (item->>'product_id') <> '' then (item->>'product_id')::uuid 
            else null 
        end,
        item->>'product_name',
        item->>'product_brand',
        (item->>'unit_price')::numeric,
        (item->>'quantity')::integer,
        (item->>'subtotal')::numeric
    from jsonb_array_elements(p_items) as item;

    return query select v_order_id, v_order_number, p_total, v_created_at;
end;
$$;
